# Configuration file for OTAR3088 GitHub Pages
## theme: lcayman@v0.2.0
## theme: dinky@v0.2.0
## theme: hacker@v0.2.0 # a dark theme
## theme: slate@v0.2.0
## theme: leap-day@v0.2.0
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
